/**
 * Human-written descriptions of what a Python package actually does, keyed by
 * its exact name in pyodide-lock.json (case-sensitive - the lock spells some
 * names in TitleCase, e.g. "Pillow", "Jinja2").
 *
 * This exists because the catalog's generated fallback ("Python library. Also
 * downloads X, Y, Z.") only describes a package's dependency footprint, never
 * its purpose. Covers the packages most people actually recognize; anything
 * missing here falls back to that generated sentence rather than going blank.
 * Not exhaustive by design - curating a real sentence for all ~345 packages,
 * many of them internal transitive dependencies nobody installs by name,
 * would mostly produce filler.
 */
export const PACKAGE_DESCRIPTIONS: Record<string, string> = {
  numpy: "N-dimensional array library and the numerical foundation most of the scientific Python stack builds on.",
  pandas: "Labeled, tabular data structures (DataFrames) for reading, cleaning, and analyzing data.",
  scipy: "Scientific computing: numerical integration, optimization, linear algebra, signal processing, and statistics.",
  matplotlib: "2D plotting library for charts, figures, and static visualizations.",
  "scikit-learn": "Classical machine learning: classification, regression, clustering, and model evaluation.",
  "scikit-image": "Image processing algorithms (filters, segmentation, feature detection) built on numpy arrays.",
  sympy: "Symbolic mathematics: algebra, calculus, and equation solving with exact (not floating-point) results.",
  networkx: "Graph and network data structures with algorithms for shortest paths, centrality, and more.",
  Pillow: "Image loading, editing, and format conversion (the modern fork of PIL).",
  requests: "The de facto standard HTTP client for making web requests in Python.",
  beautifulsoup4: "Parses HTML and XML into a navigable tree for scraping and data extraction.",
  lxml: "Fast XML and HTML parsing and processing, built on libxml2/libxslt.",
  Jinja2: "Template engine used to generate text (often HTML) by filling placeholders with data.",
  MarkupSafe: "Escapes strings for safe use in HTML/XML templates; a dependency of Jinja2.",
  sqlalchemy: "SQL toolkit and object-relational mapper (ORM) for working with databases.",
  psycopg: "PostgreSQL database driver for Python.",
  pymongo: "MongoDB database driver for Python.",
  duckdb: "Embedded analytical (OLAP) SQL database engine, run in-process like SQLite.",
  pytest: "Test framework for writing and running unit and integration tests.",
  mypy: "Static type checker that verifies type hints without running the code.",
  attrs: "Boilerplate-free way to define classes with typed attributes.",
  pydantic: "Data validation and settings management using Python type annotations.",
  click: "Toolkit for building command-line interfaces.",
  rich: "Renders styled, colorful text, tables, and progress bars in the terminal.",
  tqdm: "Adds a progress bar to loops and iterables.",
  pyyaml: "Reads and writes YAML configuration files.",
  "ruamel.yaml": "YAML parser/emitter that preserves comments and formatting on round-trip.",
  toml: "Reads and writes TOML configuration files.",
  tomli: "Minimal, read-only TOML parser.",
  simplejson: "Fast JSON encoder/decoder, a drop-in alternative to the standard library's json module.",
  ujson: "Very fast JSON encoder/decoder implemented in C.",
  orjson: "Fast, correct JSON library that serializes numpy arrays and dataclasses directly.",
  msgpack: "Efficient binary serialization format, faster and smaller than JSON.",
  cloudpickle: "Extends pickle to serialize functions, lambdas, and closures.",
  joblib: "Lightweight pipelining: caching function results and parallelizing loops.",
  "python-dateutil": "Extends the standard datetime module with powerful parsing and recurrence rules.",
  pytz: "Historical and current timezone definitions for accurate datetime handling.",
  tzdata: "The IANA time zone database, packaged for Python's zoneinfo module.",
  six: "Compatibility shims for writing code that runs on both Python 2 and 3.",
  packaging: "Utilities for parsing and comparing Python package versions and dependency specifiers.",
  setuptools: "Build and packaging tool used to define and distribute Python packages.",
  wheel: "Reference implementation of the .whl binary package format.",
  cffi: "Lets Python code call C functions and use C data types from a foreign function interface.",
  cryptography: "Cryptographic recipes and primitives: encryption, hashing, certificates, and key management.",
  bcrypt: "Password hashing using the bcrypt algorithm.",
  pynacl: "Python bindings to libsodium for encryption, signatures, and password hashing.",
  regex: "Drop-in replacement for the standard re module with additional regular-expression features.",
  "more-itertools": "Extra iterator building blocks beyond the standard itertools module.",
  toolz: "Functional programming utilities for working with iterators, functions, and dictionaries.",
  cytoolz: "Cython-accelerated implementation of the toolz functional utilities.",
  wrapt: "Decorator and wrapper utilities for building well-behaved function/class decorators.",
  deprecated: "Adds a @deprecated decorator that emits warnings when old code paths are used.",
  platformdirs: "Finds the right OS-specific folders for app config, cache, and data files.",
  distro: "Detects the Linux distribution the code is running on.",
  idna: "Implements the Internationalized Domain Names (IDNA) encoding used by networking libraries.",
  certifi: "Provides a curated bundle of root SSL/TLS certificates for verifying HTTPS connections.",
  urllib3: "Low-level HTTP client with connection pooling, retries, and TLS handling; underlies requests.",
  "charset-normalizer": "Detects the character encoding of text/byte content without external dependencies.",
  httpx: "HTTP client with both sync and async APIs and HTTP/2 support.",
  httpcore: "Low-level HTTP transport layer that httpx is built on.",
  h11: "Implements the HTTP/1.1 protocol as a pure state machine, used under httpx/httpcore.",
  aiohttp: "Asynchronous HTTP client and server built on asyncio.",
  anyio: "Compatibility layer for writing async code that runs on either asyncio or trio.",
  starlette: "Lightweight ASGI framework/toolkit for building async web services.",
  fastapi: "Web framework for building APIs quickly, using type hints for validation and docs.",
  jsonschema: "Validates JSON documents against a JSON Schema.",
  jsonpatch: "Applies RFC 6902 JSON Patch documents to modify JSON structures.",
  jsonpointer: "Resolves RFC 6901 JSON Pointer paths within a JSON document.",
  bleach: "Sanitizes HTML input to strip disallowed tags and attributes (XSS prevention).",
  html5lib: "Standards-compliant HTML parser implementing the WHATWG HTML5 spec.",
  soupsieve: "CSS selector engine used internally by BeautifulSoup.",
  cssselect: "Translates CSS selectors into XPath expressions for use with lxml.",
  fonttools: "Reads, manipulates, and writes font files (TrueType/OpenType).",
  cycler: "Composable style cyclers (e.g. color cycles) used by matplotlib.",
  contourpy: "Computes contour lines and polygons from grid data; used by matplotlib.",
  kiwisolver: "Fast implementation of the Cassowary constraint-solving algorithm, used by matplotlib layouts.",
  pyparsing: "Toolkit for building recursive-descent parsers using plain Python.",
  ply: "Python Lex-Yacc: lexer and parser generator implementing classic lex/yacc semantics.",
  bokeh: "Interactive plotting library that renders charts as JavaScript/HTML for the browser.",
  altair: "Declarative statistical visualization library based on the Vega-Lite grammar of graphics.",
  "vega-datasets": "Collection of example datasets commonly used with Vega/Vega-Lite/Altair.",
  xarray: "Labeled, multi-dimensional array structures (built on numpy) for scientific datasets.",
  zarr: "Chunked, compressed, N-dimensional array storage, often used with xarray for large datasets.",
  numcodecs: "Compression and encoding codecs used by Zarr for array storage.",
  h5py: "Reads and writes HDF5 binary files as if they were numpy arrays.",
  netcdf4: "Reads and writes NetCDF scientific data files.",
  pyarrow: "Apache Arrow bindings: columnar in-memory data and Parquet/Feather file I/O.",
  fastparquet: "Reads and writes Parquet columnar storage files.",
  polars: "Fast DataFrame library implemented in Rust, an alternative to pandas.",
  narwhals: "Compatibility layer that lets code work across pandas, polars, and other DataFrame libraries.",
  statsmodels: "Statistical modeling: regression, time series analysis, and hypothesis testing.",
  patsy: "Describes statistical models with an R-like formula syntax; used by statsmodels.",
  xgboost: "Gradient-boosted decision tree library widely used for tabular machine learning.",
  lightgbm: "Fast, memory-efficient gradient boosting framework from Microsoft.",
  numba: "Just-in-time compiles numeric Python functions to fast machine code.",
  gmpy2: "Fast arbitrary-precision arithmetic bindings to the GMP/MPFR/MPC libraries.",
  mpmath: "Arbitrary-precision floating-point arithmetic for numerical computing.",
  uncertainties: "Propagates measurement uncertainties automatically through calculations.",
  pywavelets: "Wavelet transforms for signal and image processing.",
  soundfile: "Reads and writes sound files (WAV, FLAC, OGG, and more).",
  soxr: "High-quality audio resampling via the SoX resampler library.",
  "opencv-python": "Computer vision library: image/video processing, object detection, and more.",
  imageio: "Reads and writes a wide range of image, video, and volumetric data formats.",
  "pillow-heif": "Adds HEIF/HEIC image format support on top of Pillow.",
  wordcloud: "Generates word-cloud images from text, sized by word frequency.",
  nltk: "Natural Language Toolkit: tokenization, tagging, parsing, and corpora for text processing.",
  biopython: "Tools for computational biology and bioinformatics: sequences, structures, and file formats.",
  astropy: "Core library for astronomy: coordinates, units, time systems, and FITS file I/O.",
  Cartopy: "Draws maps and geospatial data using matplotlib, with map projections and coastlines.",
  shapely: "Manipulates and analyzes planar geometric shapes (points, lines, polygons).",
  fiona: "Reads and writes vector geospatial data formats (e.g. Shapefile, GeoJSON).",
  geopandas: "Adds geometric operations to pandas DataFrames for geospatial analysis.",
  pyproj: "Cartographic projections and coordinate transformations, Python bindings to PROJ.",
  rasterio: "Reads and writes geospatial raster (gridded) data such as satellite imagery.",
  h3: "Uber's hexagonal hierarchical geospatial indexing system.",
  igraph: "High-performance graph analysis and network science library.",
  yt: "Analysis and visualization toolkit for volumetric and astrophysical simulation data.",
  "cvxpy-base": "Domain-specific language for expressing and solving convex optimization problems.",
  clarabel: "Interior-point solver for convex conic optimization problems.",
  nlopt: "Library of nonlinear optimization algorithms with a common interface.",
  swiglpk: "Python bindings to the GLPK linear programming solver.",
  casadi: "Symbolic framework for algorithmic differentiation and numerical optimization, used in control systems.",
  "boost-histogram": "Fast, flexible N-dimensional histogramming, based on the Boost.Histogram C++ library.",
  "tree-sitter": "Incremental parsing library for building syntax trees of source code.",
  "tree-sitter-python": "Python grammar for the tree-sitter parser.",
  "tree-sitter-java": "Java grammar for the tree-sitter parser.",
  "tree-sitter-go": "Go grammar for the tree-sitter parser.",
  libcst: "Parses Python source into a Concrete Syntax Tree that preserves formatting, for refactoring tools.",
  asttokens: "Annotates Python AST nodes with the exact source text and position they came from.",
  parso: "Python parser supporting error recovery, used by tools like Jedi.",
  jedi: "Autocompletion and static analysis engine for Python, used by many editors.",
  decorator: "Simplifies writing well-behaved Python decorators that preserve function signatures.",
  ipython: "Enhanced interactive Python shell with introspection, history, and rich display support.",
  prompt_toolkit: "Library for building interactive command-line interfaces and shells.",
  "matplotlib-inline": "Renders matplotlib figures inline in IPython/Jupyter-style environments.",
  traitlets: "Framework for adding validated, observable attributes to Python classes.",
  jsonschema_specifications: "Bundles the official JSON Schema specification test/meta files.",
  referencing: "Resolves references (like JSON Schema $ref) across documents.",
  "rpds-py": "Persistent (immutable) data structures implemented in Rust, used by jsonschema and others.",
  pyrsistent: "Persistent/immutable data structures for Python (maps, vectors, sets).",
  sortedcontainers: "Sorted list, dict, and set implementations with fast insertion and lookup.",
  bitarray: "Efficient array of booleans stored as individual bits.",
  frozenlist: "An immutable, hashable list-like container used internally by async libraries.",
  multidict: "Dictionary that can hold multiple values per key, used by web frameworks.",
  yarl: "Parses and manipulates URLs as a proper object rather than raw strings.",
  propcache: "Small caching utility for expensive-to-compute object properties.",
  aiosignal: "Manages ordered lists of async callbacks ('signals'), used by aiohttp.",
  "async-timeout": "Backport of asyncio's timeout context manager for older Python versions.",
  sniffio: "Detects which async library (asyncio or trio) the current code is running under.",
  exceptiongroup: "Backport of Python 3.11's ExceptionGroup for grouping multiple exceptions.",
  tblib: "Serializes tracebacks so exceptions can be re-raised in another process/thread.",
  logbook: "Structured logging library, an alternative to the standard logging module.",
  diskcache: "Disk-and-file-backed cache with a dict-like API.",
  cachetools: "Extra memoizing collections and decorators for caching function results.",
  retrying: "Adds automatic retry behavior to functions that may fail transiently.",
  "smart-open": "Opens files transparently from local disks, S3, GCS, HTTP, and more with the same API.",
  fsspec: "Unified filesystem interface for local, memory, and remote (S3, HTTP, etc.) storage backends.",
  micropip: "Pyodide's own package installer for pulling pure-Python wheels from PyPI at runtime.",
  "pyodide-http": "Patches Python's networking libraries (requests, urllib) to work inside Pyodide via fetch/XHR.",
  texttable: "Renders simple ASCII tables from tabular data.",
  svgwrite: "Creates SVG (vector graphics) files programmatically.",
  demes: "Data model and format for describing population genetics demographic models.",
  msprime: "Coalescent simulator for population genetics, used with tree-sequence data.",
  tskit: "Reads, writes, and analyzes succinct tree sequences from population genetics simulations.",
  screed: "Lightweight, indexed access to large FASTA/FASTQ sequence files.",
  pysam: "Reads and manipulates SAM/BAM/VCF bioinformatics file formats, bindings to htslib.",
  pyerfa: "Python bindings to the ERFA astronomy fundamental routines library.",
  astropy_iers_data: "Bundles Earth orientation (IERS) data tables used by astropy's time/coordinate systems.",
  openai: "Official client library for calling OpenAI's API.",
  tiktoken: "Fast tokenizer used by OpenAI models to count and split text into tokens.",
  sentencepiece: "Unsupervised text tokenizer used by many machine learning language models.",
  safetensors: "Fast, safe file format for storing machine learning model tensors.",
  ml_dtypes: "Extra numpy dtypes (like bfloat16) used by machine learning frameworks.",
  protobuf: "Google's Protocol Buffers: a compact binary format for structured data serialization.",
  mmh3: "Python bindings for the MurmurHash3 fast non-cryptographic hash function.",
  xxhash: "Bindings to the extremely fast xxHash hashing algorithm.",
  crc32c: "Computes CRC32C checksums, accelerated with hardware instructions where available.",
  crcmod: "Generates CRC (cyclic redundancy check) functions of arbitrary width and polynomial.",
  zstandard: "Bindings to the Zstandard (zstd) fast compression algorithm.",
  brotli: "Bindings to Google's Brotli compression algorithm.",
  lz4: "Bindings to the LZ4 fast compression algorithm.",
  bitstring: "Manipulates binary data as bit-level streams, easier than raw bytes.",
  cobs: "Encodes/decodes data using Consistent Overhead Byte Stuffing for reliable serial framing.",
  pyclipper: "Bindings to the Clipper polygon clipping and offsetting library.",
  pyshp: "Reads and writes ESRI Shapefiles without other geospatial dependencies.",
  xlrd: "Reads legacy .xls Excel spreadsheet files.",
  strictyaml: "Restricted, type-safe YAML parser designed to avoid YAML's common pitfalls.",
  jiter: "Fast JSON parsing library implemented in Rust, used by some AI SDKs.",
  msgspec: "Fast serialization/validation library for JSON, MessagePack, YAML, and TOML using type hints.",
  "typing-extensions": "Backports newer typing features so they can be used on older Python versions.",
  "typing-inspection": "Runtime introspection helpers for Python type hints.",
  "annotated-types": "Small, shared metadata types for use with typing.Annotated (used by pydantic).",
  pkgconfig: "Queries installed libraries' pkg-config metadata (compile flags, versions) from Python.",
  pycparser: "Parses C source code into an AST, used by cffi to process C declarations.",
  "python-calamine": "Fast reader for Excel and other spreadsheet file formats, bindings to the Rust calamine library.",
  vrplib: "Reads and writes benchmark instances for the Vehicle Routing Problem.",
  rebound: "N-body simulation code for orbital dynamics and planetary systems.",
  reboundx: "Extra physics modules (extended forces) that plug into the REBOUND simulator.",
  galpy: "Models galactic dynamics: orbits and potentials of stars in galaxies.",
  healpy: "Python bindings to HEALPix, a scheme for pixelizing the sphere used in astronomy.",
  iminuit: "Python bindings to the MINUIT numerical minimization library, used for statistical fitting.",
  optlang: "Common interface for formulating optimization problems across different solvers.",
  b2d: "Box2D physics engine bindings for 2D rigid-body simulation.",
  "pygame-ce": "Community fork of Pygame: a library for building 2D games in Python.",
  zengl: "Minimal, modern OpenGL rendering library.",
  mysqlclient: "MySQL/MariaDB database driver for Python.",
  dnspython: "DNS toolkit for querying and manipulating DNS records.",
  "python-sat": "Toolkit for prototyping SAT-based algorithms and encodings.",
  clingo: "Answer Set Programming solver for declarative logic-based problem solving.",
  "python-solvespace": "Bindings to the SolveSpace parametric 2D/3D CAD constraint solver.",
  freesasa: "Calculates solvent accessible surface areas of biomolecules.",
  phispy: "Identifies prophage regions within bacterial genomes.",
  "python-flirt": "Recognizes compiler-generated library functions in disassembled binaries (FLIRT signatures).",
  colorspacious: "Converts between color spaces and models human color perception.",
  unyt: "Attaches physical units to numpy arrays and tracks them through calculations.",
  cmyt: "Colormaps and plotting helpers for the yt astrophysics visualization package.",
  ewah_bool_utils: "Compressed bitset (EWAH) utilities used internally by yt for spatial indexing.",
  inspice: "Interfaces with the ngspice circuit simulator for electronic circuit simulation.",
  coolprop: "Thermophysical property library for fluids and refrigerants.",
  highspy: "Python bindings to the HiGHS high-performance linear/mixed-integer optimization solver.",
  "lakers-python": "Implements the EDHOC lightweight authenticated key exchange protocol for constrained devices.",
  "bilby.cython": "Cython-accelerated components of the Bilby gravitational-wave inference library.",
  pyrodigal: "Fast gene prediction in prokaryotic genomes, a Cython port of Prodigal.",
  sisl: "Tight-binding and DFT post-processing toolkit for electronic-structure calculations.",
  newick: "Parses and writes phylogenetic trees in Newick format.",
  sourmash: "Compares and searches genomic/metagenomic sequences using MinHash sketching.",
  "cbor-diag": "Converts CBOR binary data to and from its human-readable diagnostic notation.",
  peewee: "Small, expressive ORM for working with SQL databases.",
  "google-crc32c": "Hardware-accelerated CRC32C checksum implementation from Google.",
  "argon2-cffi": "Password hashing using the Argon2 algorithm, the winner of the Password Hashing Competition.",
  "memory-allocator": "Low-level manual memory allocation helper used by some Cython extensions.",
  cysignals: "Lets Cython/C code handle interrupts and crashes gracefully instead of hard-crashing Python.",
  texture2ddecoder: "Decodes compressed GPU texture formats (e.g. DXT, ETC) into raw pixel data.",
  "pytest-asyncio": "Pytest plugin for testing asyncio-based (async/await) code.",
  "pytest-benchmark": "Pytest plugin for benchmarking code and tracking performance over time.",
  pytest_httpx: "Pytest plugin for mocking HTTPX requests in tests.",
  coverage: "Measures which lines of code are executed by a test suite.",
  pluggy: "Plugin management and hook-calling framework, used internally by pytest.",
  iniconfig: "Minimal, self-contained INI file parser used internally by pytest.",
  distlib: "Low-level packaging utilities shared by pip, virtualenv, and related tools.",
  wcwidth: "Determines the terminal column width of Unicode characters for text alignment.",
  webencodings: "Implements the WHATWG character-encoding standard used by HTML parsers.",
  "pi-heif": "Reads and writes HEIF/HEIC images without requiring system libheif.",
  pyheif: "Reads HEIF/HEIC image files, decoding them into standard pixel data.",
  pyxirr: "Fast IRR/XIRR and other financial rate-of-return calculations.",
  rateslib: "Fixed income and interest-rate curve construction and derivatives pricing.",
  "audioop-lts": "Long-term-support backport of the removed standard-library audioop module.",
  nh3: "Fast HTML sanitizer, Python bindings to Mozilla's Ammonia (Rust) library.",
};
