/**
 * Opening a tunnel through the Cloudflare Worker and presenting it to the rest
 * of Node as an ordinary Duplex stream.
 *
 * The Duplex is the hinge of the whole design. Once the tunnel is a Duplex,
 * `tls.connect({ socket })` will wrap it, and `http.request({ createConnection })`
 * will speak HTTP over that - so Node's own TLS stack and its own HTTP client do
 * all the work that would otherwise have to be hand-written. The relay never
 * parses a status line or decodes a chunked body itself.
 *
 * It is also why https:// proxies work at all. The Worker does the outer TLS (to
 * the proxy) and this side does the inner TLS (to the provider). workerd cannot
 * nest one TLS session inside another, but nothing here is being asked to: each
 * runtime does exactly one.
 *
 * Uses `ws` rather than Node's global WebSocket, and that is the whole reason
 * this file has a dependency at all. The global (undici's) gives no signal that
 * a send has reached the socket, so an upload had no backpressure: a browser
 * could push a body in faster than the tunnel drained it and the excess piled
 * up in this process. `ws.send()`'s callback fires when the bytes have been
 * handed to the socket, which is what the write path below uses to hold the
 * whole chain back - through TLS, the HTTP request, Fastify and out to Caddy.
 *
 * That is the OUTBOUND half only. `ws` can also stop reading, and an earlier
 * version used that to backpressure the inbound half too; it was removed
 * because it risks batching a streamed reply into one burst at the end. The
 * note on `read()` in duplexFromWebSocket explains why, and is the thing to
 * read before adding it back.
 */
import { Duplex } from "node:stream";
import WebSocket from "ws";
import { recordStall } from "./metrics.ts";
import { deriveBucket, deriveDialKey, newNonce, sealDial } from "./crypto.ts";
import { decodeControlFrame, relayCloseCode, relayCloseMessage, type DialRequest } from "./protocol.ts";
import type { RelayProxy } from "./envelope.ts";

/** Stable string codes for the failures that never reach the Worker at all. */
export const TUNNEL_ERROR_CODES = {
  OPEN_TIMEOUT: "tunnel_open_timeout",
  RELAY_UNREACHABLE: "relay_unreachable",
  UNREADABLE_REPLY: "relay_reply_unreadable",
  UNRECOGNISED_REPLY: "relay_reply_unrecognised",
  CONNECTION_FAILED: "relay_connection_failed",
  STALLED: "tunnel_stalled",
} as const;

export class TunnelError extends Error {
  // Declared and assigned rather than written as a `readonly code` constructor
  // parameter property: those are not erasable syntax, and Node's type stripping
  // refuses them - which matters because `npm run dev` runs this source directly.
  readonly code?: number;
  /** Always set - the stable string sent to the client in the error body's `code` field. */
  readonly publicCode: string;

  constructor(message: string, code?: number, publicCode?: string) {
    super(message);
    this.name = "TunnelError";
    this.code = code;
    this.publicCode = publicCode ?? (code !== undefined ? relayCloseCode(code) : "tunnel_open_failed");
  }
}

export interface TunnelOptions {
  purpose?: "catalog";
  signal?: AbortSignal;
  workerUrl: string;
  secret: string;
  proxy: RelayProxy;
  target: { host: string; port: number };
  openTimeoutMs?: number;
  /** Opt-in diagnostic logging. See `RelayConfig.debugLog`. */
  debugLog?: boolean;
  /** Correlation id for diagnostic logging, generated by the caller. */
  requestId?: string;
  /**
   * The caller's own rate-limit key - the same value handleRelay keys its
   * limiter on. Hashed into an opaque bucket before it is sealed; the raw
   * value never leaves this process. Omitted, the Worker falls back to keying
   * on this machine's address, which is one bucket for every user at once.
   */
  clientKey?: string;
}

/**
 * Emits one structured JSON line naming which branch of tunnel setup failed,
 * for diagnostics. `branch` and `closeCode` are fixed, enum-like values -
 * never the target, proxy, headers or dial content - so this cannot trip
 * `verify-relay.ts`'s privacy regex or leak request data.
 */
function logTunnelFail(debugLog: boolean | undefined, requestId: string | undefined, branch: string, closeCode?: number): void {
  if (!debugLog) return;
  console.error(JSON.stringify({ evt: "tunnel_open_fail", branch, rid: requestId, closeCode }));
}

/**
 * The Worker's own worst case, end to end, is bounded by two constants in
 * inbrowser-relay/src/index.ts: firstBinaryFrame()'s 10s dial-frame wait plus
 * HANDSHAKE_TIMEOUT_MS's 15s handshake wait = 25s before it guarantees an
 * ERROR frame or close. This budget must exceed that AND the network time to
 * reach the Worker in the first place, because the timer below starts before
 * the WebSocket even connects - so it pays for DNS+TCP+TLS to Cloudflare's
 * edge and the WS upgrade round-trip on top of the Worker's own 25s. If
 * either constant in that file changes, update this one to match.
 */
const DEFAULT_OPEN_TIMEOUT_MS = 35_000;

/**
 * Resolves once the Worker has answered READY, meaning the proxy handshake
 * succeeded and the stream now carries tunnel bytes. Rejects with the Worker's
 * own message when it answered ERROR, so a proxy's "407 rejected these
 * credentials" survives all the way to the user's Settings panel.
 */
export async function openTunnel(options: TunnelOptions): Promise<Duplex> {
  const started = Date.now();
  const throwIfCancelled = () => {
    if (options.signal?.aborted) throw new TunnelError("Tunnel cancelled.", undefined, "tunnel_cancelled");
  };
  throwIfCancelled();
  const {
    workerUrl,
    secret,
    proxy,
    target,
    openTimeoutMs = DEFAULT_OPEN_TIMEOUT_MS,
    debugLog,
    requestId,
    clientKey,
  } = options;

  const key = await deriveDialKey(secret);
  throwIfCancelled();
  const dial: DialRequest = {
    ...(options.purpose ? { purpose: options.purpose } : {}),
    ts: Date.now(),
    nonce: newNonce(),
    protocol: proxy.protocol,
    host: proxy.host,
    port: proxy.port,
    username: proxy.username,
    password: proxy.password,
    target,
    bucket: clientKey ? await deriveBucket(secret, clientKey) : undefined,
  };
  const frame = await sealDial(key, dial);
  throwIfCancelled();
  if (Date.now() - started >= openTimeoutMs) {
    throw new TunnelError("The relay did not respond in time.", undefined, TUNNEL_ERROR_CODES.OPEN_TIMEOUT);
  }

  const ws = new WebSocket(workerUrl, {
    // The Worker sets no_web_socket_compression, and every byte here is either
    // a sealed dial or somebody else's TLS session - already high entropy, so
    // compression would only cost CPU.
    perMessageDeflate: false,
    // Default is 100 MiB. Nothing legitimate on this socket exceeds the
    // Worker's own 64 KiB chunking, so a frame far above that is a bug or an
    // attempt at one, and refusing it early bounds what a single frame can
    // make this process allocate.
    maxPayload: 1024 * 1024,
    handshakeTimeout: 10_000,
    // Binary only; UTF-8 validation would be wasted work on every frame.
    skipUTF8Validation: true,
  });
  // Deliberately NOT binaryType = "arraybuffer". That was carried over from the
  // global WebSocket, which had no other option, and it is a trap here: `ws`'s
  // toArrayBuffer() hands back its own internal `buf.buffer` whenever the frame
  // fills its backing store, and wrapping that in Buffer.from() makes a VIEW,
  // not a copy - so a later frame can overwrite bytes we have already pushed
  // but TLS has not yet read. The default, nodebuffer, gives a Buffer we can
  // push straight through with no conversion and no aliasing.

  return new Promise<Duplex>((resolve, reject) => {
    let settled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const cancel = () => { if (!settled) finish(new TunnelError("Tunnel cancelled.", undefined, "tunnel_cancelled")); };

    const finish = (err: Error | null, duplex?: Duplex, branch?: string) => {
      if (settled) return;
      settled = true;
      options.signal?.removeEventListener("abort", cancel);
      clearTimeout(timer);
      if (err) {
        if (err instanceof TunnelError && branch) logTunnelFail(debugLog, requestId, branch, err.code);
        // Close on every rejection path, not just the timeout. A dial that the
        // Worker refuses - a bad secret, a blocked address, a proxy that will
        // not answer - would otherwise leave its WebSocket open with nothing
        // holding a reference, so a relay hitting a run of failures would
        // accumulate one leaked socket per attempt.
        try {
          ws.terminate();
        } catch {
          /* never opened, or already closing */
        }
        reject(err);
      } else {
        resolve(duplex!);
      }
    };

    ws.on("open", () => {
      if (settled) return;
      ws.send(frame, { binary: true });
    });

    ws.on("error", () => {
      finish(
        new TunnelError("Could not reach the relay.", undefined, TUNNEL_ERROR_CODES.RELAY_UNREACHABLE),
        undefined,
        "ws_error_pre_ready"
      );
    });

    ws.on("close", (code: number) => {
      // A close before READY is the Worker refusing the dial. After READY the
      // duplex owns the socket and handles close itself.
      finish(code >= 4000
        ? new TunnelError(relayCloseMessage(code), code)
        : new TunnelError("The relay connection failed.", undefined, TUNNEL_ERROR_CODES.CONNECTION_FAILED),
      undefined, "ws_close_pre_ready");
    });

    // The first message is the control frame; everything after it is tunnel
    // data, handled by the duplex below.
    const onControl = (data: WebSocket.RawData) => {
      ws.off("message", onControl);
      if (settled) return;
      let frameBytes: Uint8Array;
      try {
        frameBytes = toBuffer(data);
      } catch {
        finish(
          new TunnelError("The relay sent an unreadable reply.", undefined, TUNNEL_ERROR_CODES.UNREADABLE_REPLY),
          undefined,
          "unreadable_control_frame"
        );
        return;
      }

      let control: ReturnType<typeof decodeControlFrame>;
      try {
        control = decodeControlFrame(frameBytes);
      } catch {
        finish(
          new TunnelError("The relay sent an unrecognised reply.", undefined, TUNNEL_ERROR_CODES.UNRECOGNISED_REPLY),
          undefined,
          "unrecognised_control_frame"
        );
        return;
      }

      if (control.kind === "error") {
        finish(new TunnelError(control.message, control.code), undefined, "worker_error_frame");
        return;
      }
      finish(null, duplexFromWebSocket(ws, debugLog, requestId));
    };

    ws.on("message", onControl);
    timer = setTimeout(() => {
      finish(new TunnelError("The relay did not respond in time.", undefined, TUNNEL_ERROR_CODES.OPEN_TIMEOUT), undefined, "timeout");
    }, Math.max(1, openTimeoutMs - (Date.now() - started)));
    // Register only after every callback and the timer exist. Recheck because
    // the signal may have fired during key derivation or listener setup.
    options.signal?.addEventListener("abort", cancel, { once: true });
    if (options.signal?.aborted) cancel();
  });
}

/**
 * `ws` hands a message over as a Buffer, an array of Buffers (a fragmented
 * message) or an ArrayBuffer, depending on how it arrived. Concatenating a
 * fragmented message rather than pushing the pieces is not optional: a caller
 * reading a control frame needs the whole frame, and the tunnel needs the
 * bytes in order with no gaps.
 */
function toBuffer(data: WebSocket.RawData): Buffer {
  if (Buffer.isBuffer(data)) return data;
  // Only reachable for a fragmented message, where `ws` hands over the pieces.
  if (Array.isArray(data)) return Buffer.concat(data);
  // Not expected with the default binaryType, but copying rather than viewing
  // is the safe reading of an ArrayBuffer whose owner may reuse it.
  return Buffer.from(new Uint8Array(data as ArrayBuffer));
}

/**
 * A single `write()` here becomes a single `ws.send()`, and the tunnel is a
 * raw byte stream with no per-message framing beyond the initial dial frame
 * - the Worker on the other end just forwards whatever bytes arrive onto the
 * TCP socket, in order. That makes chunking here fully transparent to it,
 * which matters because a large request body (an image attachment's base64
 * payload, easily hundreds of KB) can arrive from Fastify's own incoming
 * stream as far fewer, far larger reads than a small text turn ever does -
 * especially once Cloudflare's edge sits in front of this server and
 * rebatches the client's upload before handing it to the origin. A single
 * oversized WebSocket message is exactly the kind of thing a Workers-hosted
 * relay has no good option but to drop the connection over, which surfaces
 * to the browser as the tunnel closing mid-request - only for requests large
 * enough to hit it, which a plain text message never is.
 */
const MAX_WS_CHUNK_BYTES = 512 * 1024;

/**
 * How long the readable side may sit over its high-water mark, with the socket
 * paused, before the tunnel is given up on. Under the Worker's 60s idle cap and
 * well under forward.ts's 120s request timeout, so a genuinely stuck consumer
 * is named here rather than surfacing later as a generic timeout.
 */
const STALL_LIMIT_MS = 20_000;

/** How often the stall deadline is checked. Coarse on purpose - it is a deadline, not a measurement. */
const STALL_CHECK_MS = 2_000;

function duplexFromWebSocket(ws: WebSocket, debugLog?: boolean, requestId?: string): Duplex {
  /** When the readable side first went over its watermark, or 0 while healthy. */
  let overSince = 0;

  const duplex = new Duplex({
    /**
     * Nothing to do, and that is deliberate.
     *
     * An earlier version paused the WebSocket's socket whenever `push()`
     * reported backpressure and resumed only from here, which is the textbook
     * shape for a Duplex being pulled by a consumer. It is the wrong shape for
     * THIS one: `tls.connect({ socket })` does not pull, it wraps the stream in
     * Node's JSStreamSocket and drives it through 'data' with its own
     * pause()/resume(), so whether this is re-entered promptly after a pause is
     * not ours to determine. A streamed reply that arrives in one burst at the
     * end instead of token by token is the single worst failure this component
     * has, and it is not worth risking for flow control that only matters to a
     * consumer which has stopped reading entirely - a case the stall deadline
     * below already handles, without touching delivery of the healthy case.
     *
     * Do not reintroduce an inbound pause here without a test that proves
     * arrivals stay spread across the response (verify-relay.ts has one).
     */
    read() {},

    /**
     * The entire outbound half of the flow control is the placement of
     * `callback`. Passing it to `ws.send` instead of calling it immediately
     * means Node will not hand us another chunk until these bytes have reached
     * the socket - and because `_write` is not re-entered before `callback`,
     * ordering stops depending on `ws`'s internal queue and becomes a property
     * of the stream itself.
     *
     * That one change propagates the whole way back: the provider's TLS socket
     * stops draining, `ClientRequest` stops accepting, `body.pipe(request)`
     * pauses, Fastify stops reading the incoming request, and Caddy
     * backpressures the browser's upload.
     */
    write(chunk: Buffer, _encoding, callback) {
      if (ws.readyState !== WebSocket.OPEN) {
        callback(new TunnelError("The relay connection failed.", undefined, TUNNEL_ERROR_CODES.CONNECTION_FAILED));
        return;
      }
      const pieces: Buffer[] = [];
      if (chunk.length <= MAX_WS_CHUNK_BYTES) {
        pieces.push(chunk);
      } else {
        for (let offset = 0; offset < chunk.length; offset += MAX_WS_CHUNK_BYTES) {
          pieces.push(chunk.subarray(offset, offset + MAX_WS_CHUNK_BYTES));
        }
      }
      let pending = pieces.length;
      let failed = false;
      for (const piece of pieces) {
        ws.send(piece, { binary: true }, (err) => {
          if (failed) return;
          if (err) {
            failed = true;
            callback(err);
            return;
          }
          if (--pending === 0) callback();
        });
      }
    },

    final(callback) {
      try {
        ws.close(1000);
      } catch {
        /* already closing */
      }
      callback();
    },

    destroy(err, callback) {
      clearInterval(stallTimer);
      try {
        ws.close();
      } catch {
        /* already closing */
      }
      callback(err);
    },
  });

  ws.on("message", (data: WebSocket.RawData) => {
    // Pushed unconditionally. push() returning false is recorded for the stall
    // deadline below, but is NOT acted on by pausing the socket - see the note
    // on read() above for why.
    if (!duplex.push(toBuffer(data))) {
      if (overSince === 0) overSince = Date.now();
    } else {
      overSince = 0;
    }
  });

  /**
   * A consumer that never resumes.
   *
   * Flow control alone converts "buffer without bound here" into "stop reading
   * and hold the tunnel open forever", which is better but still not good: the
   * bytes then queue in the Worker instead, and a Worker isolate's memory is
   * shared with every other tunnel that happens to live in it. One browser
   * that stops reading could take out unrelated tunnels. Dropping our own
   * tunnel is the only thing this side can do about it, so it does that.
   *
   * The deadline sits under the Worker's 60s idle cap and well under
   * forward.ts's 120s, so this fires first and the failure has a name.
   */
  const stallTimer = setInterval(() => {
    // Healthy again, or never unhealthy: the consumer has caught up.
    if (overSince === 0 || duplex.readableLength === 0) {
      overSince = 0;
      return;
    }
    if (Date.now() - overSince < STALL_LIMIT_MS) return;
    clearInterval(stallTimer);
    recordStall();
    fail(new TunnelError("The connection stalled and was closed.", undefined, TUNNEL_ERROR_CODES.STALLED));
  }, STALL_CHECK_MS);
  stallTimer.unref();

  /**
   * A transport error can arrive after the consumer is gone - the response has
   * been fully read, `tunnel.destroy()` has run, and only then does the
   * WebSocket report its close. At that point no consumer is listening, and an
   * `error` event with no listener takes the whole process down. Guarding on
   * `destroyed` stops the second teardown, and the no-op listener guarantees
   * one is always attached. Without both, the relay dies on a perfectly
   * ordinary connection close.
   */
  duplex.on("error", () => {});

  const fail = (err: Error) => {
    if (!duplex.destroyed) duplex.destroy(err);
  };

  /**
   * Three outcomes, and the middle one is easy to get wrong.
   *
   *   >= 4000  the Worker closing deliberately, with a reason worth keeping.
   *   1000/1005 a normal close: the peer is finished, so EOF the readable side.
   *   anything else - 1001, and above all 1006 - the connection dropped.
   *
   * 1006 is what arrives when the far end goes away without a close frame, and
   * it must NOT be treated as a clean EOF: pushing null there tells the HTTP
   * client the response ended normally, so a truncated reply is reported as a
   * generic provider failure instead of as the transport failure it is. The
   * `ws` client surfaces this where the old global WebSocket raised an error
   * event, which is why this distinction has to be made explicitly here.
   */
  ws.on("close", (code: number) => {
    clearInterval(stallTimer);
    if (code >= 4000) {
      logTunnelFail(debugLog, requestId, "post_ready_close", code);
      fail(new TunnelError(relayCloseMessage(code), code));
      return;
    }
    if (code !== 1000 && code !== 1005) {
      logTunnelFail(debugLog, requestId, "post_ready_abnormal_close", code);
      fail(new TunnelError("The relay connection failed.", undefined, TUNNEL_ERROR_CODES.CONNECTION_FAILED));
      return;
    }
    if (!duplex.destroyed) duplex.push(null);
  });

  ws.on("error", () => {
    clearInterval(stallTimer);
    logTunnelFail(debugLog, requestId, "post_ready_ws_error");
    fail(new TunnelError("The relay connection failed.", undefined, TUNNEL_ERROR_CODES.CONNECTION_FAILED));
  });

  return duplex;
}
