/**
 * Opening a tunnel through the Cloudflare Worker and presenting it to the rest
 * of Node as an ordinary Duplex stream.
 *
 * The Duplex is the hinge of the whole design. Once the tunnel is a Duplex,
 * `tls.connect({ socket })` will wrap it, and `http.request({ createConnection })`
 * will speak HTTP over that - so Node's own TLS stack and its own HTTP client do
 * all the work that would otherwise have to be hand-written. The relay never
 * parses a status line or decodes a chunked body itself.
 *
 * It is also why https:// proxies work at all. The Worker does the outer TLS (to
 * the proxy) and this side does the inner TLS (to the provider). workerd cannot
 * nest one TLS session inside another, but nothing here is being asked to: each
 * runtime does exactly one.
 *
 * Uses the WebSocket global, which Node exposes from v22 - the relay has no
 * runtime dependencies at all, deliberately, since this is the one component
 * that handles plaintext.
 */
import { Duplex } from "node:stream";
import { deriveDialKey, newNonce, sealDial } from "./crypto.ts";
import { decodeControlFrame, relayCloseCode, relayCloseMessage, type DialRequest } from "./protocol.ts";
import type { RelayProxy } from "./envelope.ts";

/** Stable string codes for the failures that never reach the Worker at all. */
export const TUNNEL_ERROR_CODES = {
  OPEN_TIMEOUT: "tunnel_open_timeout",
  RELAY_UNREACHABLE: "relay_unreachable",
  UNREADABLE_REPLY: "relay_reply_unreadable",
  UNRECOGNISED_REPLY: "relay_reply_unrecognised",
  CONNECTION_FAILED: "relay_connection_failed",
} as const;

export class TunnelError extends Error {
  // Declared and assigned rather than written as a `readonly code` constructor
  // parameter property: those are not erasable syntax, and Node's type stripping
  // refuses them - which matters because `npm run dev` runs this source directly.
  readonly code?: number;
  /** Always set - the stable string sent to the client in the error body's `code` field. */
  readonly publicCode: string;

  constructor(message: string, code?: number, publicCode?: string) {
    super(message);
    this.name = "TunnelError";
    this.code = code;
    this.publicCode = publicCode ?? (code !== undefined ? relayCloseCode(code) : "tunnel_open_failed");
  }
}

export interface TunnelOptions {
  workerUrl: string;
  secret: string;
  proxy: RelayProxy;
  target: { host: string; port: number };
  openTimeoutMs?: number;
  /** Opt-in diagnostic logging. See `RelayConfig.debugLog`. */
  debugLog?: boolean;
  /** Correlation id for diagnostic logging, generated by the caller. */
  requestId?: string;
}

/**
 * Emits one structured JSON line naming which branch of tunnel setup failed,
 * for diagnostics. `branch` and `closeCode` are fixed, enum-like values -
 * never the target, proxy, headers or dial content - so this cannot trip
 * `verify-relay.ts`'s privacy regex or leak request data.
 */
function logTunnelFail(debugLog: boolean | undefined, requestId: string | undefined, branch: string, closeCode?: number): void {
  if (!debugLog) return;
  console.error(JSON.stringify({ evt: "tunnel_open_fail", branch, rid: requestId, closeCode }));
}

/**
 * The Worker's own worst case, end to end, is bounded by two constants in
 * inbrowser-relay/src/index.ts: firstBinaryFrame()'s 10s dial-frame wait plus
 * HANDSHAKE_TIMEOUT_MS's 15s handshake wait = 25s before it guarantees an
 * ERROR frame or close. This budget must exceed that AND the network time to
 * reach the Worker in the first place, because the timer below starts before
 * the WebSocket even connects - so it pays for DNS+TCP+TLS to Cloudflare's
 * edge and the WS upgrade round-trip on top of the Worker's own 25s. If
 * either constant in that file changes, update this one to match.
 */
const DEFAULT_OPEN_TIMEOUT_MS = 35_000;

/**
 * Resolves once the Worker has answered READY, meaning the proxy handshake
 * succeeded and the stream now carries tunnel bytes. Rejects with the Worker's
 * own message when it answered ERROR, so a proxy's "407 rejected these
 * credentials" survives all the way to the user's Settings panel.
 */
export async function openTunnel(options: TunnelOptions): Promise<Duplex> {
  const { workerUrl, secret, proxy, target, openTimeoutMs = DEFAULT_OPEN_TIMEOUT_MS, debugLog, requestId } = options;

  const key = await deriveDialKey(secret);
  const dial: DialRequest = {
    ts: Date.now(),
    nonce: newNonce(),
    protocol: proxy.protocol,
    host: proxy.host,
    port: proxy.port,
    username: proxy.username,
    password: proxy.password,
    target,
  };
  const frame = await sealDial(key, dial);

  const ws = new WebSocket(workerUrl);
  ws.binaryType = "arraybuffer";

  return new Promise<Duplex>((resolve, reject) => {
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      try {
        ws.close();
      } catch {
        /* not open yet */
      }
      logTunnelFail(debugLog, requestId, "timeout");
      reject(new TunnelError("The relay did not respond in time.", undefined, TUNNEL_ERROR_CODES.OPEN_TIMEOUT));
    }, openTimeoutMs);

    const finish = (err: Error | null, duplex?: Duplex, branch?: string) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (err) {
        if (err instanceof TunnelError && branch) logTunnelFail(debugLog, requestId, branch, err.code);
        // Close on every rejection path, not just the timeout. A dial that the
        // Worker refuses - a bad secret, a blocked address, a proxy that will
        // not answer - would otherwise leave its WebSocket open with nothing
        // holding a reference, so a relay hitting a run of failures would
        // accumulate one leaked socket per attempt.
        try {
          ws.close();
        } catch {
          /* never opened, or already closing */
        }
        reject(err);
      } else {
        resolve(duplex!);
      }
    };

    ws.addEventListener("open", () => {
      ws.send(frame);
    });

    ws.addEventListener("error", () => {
      finish(
        new TunnelError("Could not reach the relay.", undefined, TUNNEL_ERROR_CODES.RELAY_UNREACHABLE),
        undefined,
        "ws_error_pre_ready"
      );
    });

    ws.addEventListener("close", (event) => {
      // A close before READY is the Worker refusing the dial. After READY the
      // duplex owns the socket and handles close itself.
      finish(new TunnelError(relayCloseMessage(event.code), event.code), undefined, "ws_close_pre_ready");
    });

    // The first message is the control frame; everything after it is tunnel
    // data, handled by the duplex below.
    const onControl = (event: MessageEvent) => {
      ws.removeEventListener("message", onControl as EventListener);
      let frameBytes: Uint8Array;
      try {
        frameBytes = new Uint8Array(event.data as ArrayBuffer);
      } catch {
        finish(
          new TunnelError("The relay sent an unreadable reply.", undefined, TUNNEL_ERROR_CODES.UNREADABLE_REPLY),
          undefined,
          "unreadable_control_frame"
        );
        return;
      }

      let control: ReturnType<typeof decodeControlFrame>;
      try {
        control = decodeControlFrame(frameBytes);
      } catch {
        finish(
          new TunnelError("The relay sent an unrecognised reply.", undefined, TUNNEL_ERROR_CODES.UNRECOGNISED_REPLY),
          undefined,
          "unrecognised_control_frame"
        );
        return;
      }

      if (control.kind === "error") {
        finish(new TunnelError(control.message, control.code), undefined, "worker_error_frame");
        return;
      }
      finish(null, duplexFromWebSocket(ws, debugLog, requestId));
    };

    ws.addEventListener("message", onControl as EventListener);
  });
}

function duplexFromWebSocket(ws: WebSocket, debugLog?: boolean, requestId?: string): Duplex {
  const duplex = new Duplex({
    // Data is pushed as it arrives rather than pulled. There is no usable
    // backpressure signal on a WebSocket in either direction, so the relay
    // bounds memory with request caps instead of flow control.
    read() {},
    write(chunk: Buffer, _encoding, callback) {
      try {
        ws.send(chunk);
        callback();
      } catch (err) {
        callback(err as Error);
      }
    },
    final(callback) {
      try {
        ws.close(1000);
      } catch {
        /* already closing */
      }
      callback();
    },
    destroy(err, callback) {
      try {
        ws.close();
      } catch {
        /* already closing */
      }
      callback(err);
    },
  });

  ws.addEventListener("message", (event) => {
    const data = event.data;
    const buf =
      data instanceof ArrayBuffer
        ? Buffer.from(data)
        : typeof data === "string"
          ? Buffer.from(data, "utf8")
          : Buffer.from(data as unknown as Uint8Array);
    duplex.push(buf);
  });

  /**
   * A transport error can arrive after the consumer is gone - the response has
   * been fully read, `tunnel.destroy()` has run, and only then does the
   * WebSocket report its close. At that point no consumer is listening, and an
   * `error` event with no listener takes the whole process down. Guarding on
   * `destroyed` stops the second teardown, and the no-op listener guarantees
   * one is always attached. Without both, the relay dies on a perfectly
   * ordinary connection close.
   */
  duplex.on("error", () => {});

  const fail = (err: Error) => {
    if (!duplex.destroyed) duplex.destroy(err);
  };

  ws.addEventListener("close", (event) => {
    if (event.code !== 1000 && event.code >= 4000) {
      logTunnelFail(debugLog, requestId, "post_ready_close", event.code);
      fail(new TunnelError(relayCloseMessage(event.code), event.code));
      return;
    }
    if (!duplex.destroyed) duplex.push(null);
  });

  ws.addEventListener("error", () => {
    logTunnelFail(debugLog, requestId, "post_ready_ws_error");
    fail(new TunnelError("The relay connection failed.", undefined, TUNNEL_ERROR_CODES.CONNECTION_FAILED));
  });

  return duplex;
}
